import { computeFairnessOverview } from "@/lib/fairness";
import { TRAIT_LABELS } from "@/lib/tasks";
import { readStore } from "@/lib/storage";
import type { TraitKey } from "@/lib/types";

export const dynamic = "force-dynamic";

const traitKeys = Object.keys(TRAIT_LABELS) as TraitKey[];

export default async function AdminPage() {
  const store = await readStore();
  const fairness = computeFairnessOverview(
    store.sessions,
    store.reports,
    "hearingContext",
  );

  return (
    <main className="page stack">
      <section className="hero">
        <div className="stack">
          <span className="eyebrow">Governance console</span>
          <h1>Auditability and fairness hooks.</h1>
          <p className="lede">
            Inspect role configuration, consented fairness-monitoring cohorts,
            and system audit events generated by candidate and scoring activity.
          </p>
        </div>
        <div className="card grid two">
          <div className="metric">
            <strong>{fairness.eligibleSessions}</strong>
            <span>Fairness-eligible sessions</span>
          </div>
          <div className="metric">
            <strong>{fairness.groups.length}</strong>
            <span>Observed context groups</span>
          </div>
          <div className="metric">
            <strong>{fairness.largestObservedGap}</strong>
            <span>Largest trait gap</span>
          </div>
          <div className="metric">
            <strong>{store.auditLog.length}</strong>
            <span>Audit entries</span>
          </div>
        </div>
      </section>

      <section className="grid two">
        <div className="card stack">
          <h2>Fairness monitoring hook</h2>
          <p>
            Current monitor: <strong>{fairness.monitoredAttribute}</strong>.
            Values are aggregate-only and require sufficient sample sizes before
            interpretation.
          </p>
          {fairness.groups.length === 0 ? (
            <div className="warning">
              No eligible completed sessions yet. Candidates must opt in to
              fairness monitoring and complete the assessment.
            </div>
          ) : (
            fairness.groups.map((group) => (
              <div className="panel stack" key={group.group}>
                <h3>
                  {group.group} ({group.count})
                </h3>
                {traitKeys.map((traitKey) => (
                  <div key={traitKey}>
                    <strong>
                      {TRAIT_LABELS[traitKey]} -{" "}
                      {group.averageTraits[traitKey]}
                    </strong>
                    <div className="score-bar" aria-hidden="true">
                      <span
                        style={{ width: `${group.averageTraits[traitKey]}%` }}
                      />
                    </div>
                  </div>
                ))}
              </div>
            ))
          )}
          {fairness.notes.map((note) => (
            <div className="warning" key={note}>
              {note}
            </div>
          ))}
        </div>

        <div className="card stack">
          <h2>Role configuration matrix</h2>
          {store.roleConfigs.map((role) => (
            <div className="panel stack" key={role.id}>
              <h3>{role.label}</h3>
              <p>{role.description}</p>
              {traitKeys.map((traitKey) => (
                <div key={traitKey}>
                  <strong>
                    {TRAIT_LABELS[traitKey]} -{" "}
                    {Math.round(role.traitWeights[traitKey] * 100)}%
                  </strong>
                  <div className="score-bar" aria-hidden="true">
                    <span
                      style={{ width: `${role.traitWeights[traitKey] * 100}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          ))}
        </div>
      </section>

      <section className="card stack">
        <h2>Audit log</h2>
        {store.auditLog.length === 0 ? (
          <div className="warning">No audit events recorded yet.</div>
        ) : (
          <div style={{ overflowX: "auto" }}>
            <table className="table">
              <thead>
                <tr>
                  <th>Time</th>
                  <th>Actor</th>
                  <th>Action</th>
                  <th>Entity</th>
                  <th>Metadata</th>
                </tr>
              </thead>
              <tbody>
                {store.auditLog.slice(0, 30).map((entry) => (
                  <tr key={entry.id}>
                    <td>{new Date(entry.createdAt).toLocaleString()}</td>
                    <td>{entry.actor}</td>
                    <td>{entry.action}</td>
                    <td>{entry.entityId}</td>
                    <td>
                      <code>{JSON.stringify(entry.metadata)}</code>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </main>
  );
}
